### ISSUE TITLE
Waveshare 1.44inch LCD HAT support? (128x128, 4-wire SPI, ST7735S)

### ISSUE THREAD

**Issue by FiberMoose** [beboxos/P4wnP1_ALOA_OLED_MENU_V2#6]
**What would it take to introduce support for the waveshare 1.44inch LCD HAT?**
**Product page:** https://www.waveshare.com/wiki/1.44inch_LCD_HAT
**Specs/Manual:** https://www.waveshare.com/w/upload/1/1c/1.44inch_LCD_HAT_User_Manual_EN.pdf

Does this project already support this model LCD Hat?

The issue i am having is once i run runmenu.py or guy.py, the screen flashes/strobes white till i kill the PID

**Comment by clucode** [comment]
I'm having the same issue. Any luck with a fix?
